import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Support JSON request bodies
  app.use(express.json({ limit: '15mb' }));

  // AI powered offshore certificates audit endpoint
  app.post('/api/certificates/ai-audit', async (req, res) => {
    try {
      const { certificates = [], employees = [] } = req.body;

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        // Fallback local robust HSE intelligence reporting if API Key is not set yet
        console.warn('GEMINI_API_KEY is not defined. Using local rule-based safety engine fallback.');
        
        // Let's run a highly realistic compliance evaluation locally
        let expiredCount = 0;
        let expiringCount = 0;
        const now = new Date();
        const threeMonthsFromNow = new Date();
        threeMonthsFromNow.setMonth(now.getMonth() + 3);

        const auditItems: string[] = [];

        certificates.forEach((c: any) => {
          const expDate = new Date(c.expiryDate);
          if (expDate < now) {
            expiredCount++;
            auditItems.push(`❌ **${c.userName}**'s **${c.certType}** certificate expired on ${c.expiryDate}. **HSE RISK**: Gated access prohibited for offshore platforms.`);
          } else if (expDate < threeMonthsFromNow) {
            expiringCount++;
            auditItems.push(`⚠️ **${c.userName}**'s **${c.certType}** certificate expires on ${c.expiryDate} (within 3 months). **HSE RISK**: Requires immediate renewal scheduling.`);
          }
        });

        const missingCerts: string[] = [];
        employees.filter((emp: any) => emp.role === 'employee').forEach((emp: any) => {
          const myCerts = certificates.filter((c: any) => c.userId === emp.id);
          const hasBosiet = myCerts.some((c: any) => c.certType === 'BOSIET');
          const hasMedical = myCerts.some((c: any) => c.certType === 'PETRONAS Medical');
          const hasOgsp = myCerts.some((c: any) => c.certType === 'OGSP');

          if (!hasBosiet) missingCerts.push(`🚫 **${emp.name}**: Missing mandatory **BOSIET** certification (Offshore survival prerequisite).`);
          if (!hasMedical) missingCerts.push(`🚫 **${emp.name}**: Missing mandatory **PETRONAS Medical** certification.`);
          if (!hasOgsp) missingCerts.push(`🚫 **${emp.name}**: Missing **OGSP** Oil & Gas Safety Passport.`);
        });

        const report = `### 📋 HSE Compliance Audit Report (Local Rules Fallback)
*Generated by the local HSE Rules Engine because GEMINI_API_KEY was not configured.*

#### 🚨 Critical Platform Alert Summary
- **Expired Certificates**: ${expiredCount}
- **Expiring within 3 months**: ${expiringCount}
- **Missing Core Credentials**: ${missingCerts.length}

---

#### 📌 Detailed Certificate Validity Scan
${auditItems.length > 0 ? auditItems.join('\n') : '✅ All uploaded offshore credentials are currently valid and unexpired.'}

---

#### 🚫 Prerequisite Deficiency Scan (Mandated for Offshore Malaysia)
${missingCerts.length > 0 ? missingCerts.join('\n') : '✅ All personnel meet basic prerequisites (BOSIET, Medical, OGSP) for offshore mobilization.'}

---

#### 💡 HSE Compliance Officer Actions
1. **Mobilization Hold**: Freeze offshore deployment for any employee with an expired certificate.
2. **Auto-Reminders**: Issued renewal triggers to employees with expiring credentials.
3. **Smart Scheduling**: Coordinate next-available PETRONAS Approved Medical Examiner slots in Miri or Kemaman.`;

        return res.json({ report });
      }

      // Initialize the Gemini SDK safely using the server-side key
      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          },
        },
      });

      // Construct a highly detailed compliance prompt about Offshore Malaysia requirements (PETRONAS, SHELL, BOSIET, HUET, CIDB)
      const prompt = `You are an expert HSE Offshore Operations Auditor specialized in Malaysian Oil & Gas industry standards (PETRONAS Procedures and Guidelines for HSE, SHELL Safety Standards, BOSIET/FOET emergency response, and CIDB Malaysia Green Card certifications).

Conduct a comprehensive HSE Compliance Audit on the following personnel and certificates data:

EMPLOYEE DATABASE:
${JSON.stringify(employees.map((e: any) => ({ id: e.id, name: e.name, email: e.email, role: e.role, phone: e.phone, kinName: e.kinName, kinPhone: e.kinPhone })), null, 2)}

ACTIVE CERTIFICATES DATABASE:
${JSON.stringify(certificates.map((c: any) => ({ id: c.id, userId: c.userId, userName: c.userName, certType: c.certType, issueDate: c.issueDate, expiryDate: c.expiryDate, fileName: c.fileName })), null, 2)}

CURRENT TIME: ${new Date().toISOString()}

Provide a highly professional, beautifully structured markdown compliance report containing:
1. **EXECUTIVE OVERVIEW**: Summary metrics (Total crew, Expired certificates, Expiring within 3 months, Deficiencies in mandatory certifications).
2. **CRITICAL RISK ANALYSIS**: Bullet points listing each specific expired/expiring certificate, indicating employee name, certificate, and the exact offshore deployment risk (e.g. survival training expired prevents boarding helicopters).
3. **MANDATORY CERTIFICATE HOLES**: Find which offshore employees are missing mandatory Malaysian offshore core items (BOSIET, PETRONAS Medical, OGSP Oil & Gas Safety Passport, or CIDB Green Card).
4. **EMERGENCY CONTACTS / NEXT OF KIN CHECK**: Note if any offshore employee lacks next of kin information (Crucial for Malaysian HSE Offshore regulations).
5. **ACTIONABLE RECOMMENDATIONS**: Formulate concrete HSE tasks for the manager (such as booking AME doctor appointments, scheduling HUET/FOET simulator runs, or frozen boarding passes).

Write the report in a direct, commanding HSE auditor style. Use professional formatting, emoji alerts, and clear sections.`;

      const response = await ai.models.generateContent({
        model: 'gemini-3.5-flash',
        contents: prompt,
      });

      const report = response.text || 'Unable to generate report from Gemini API.';
      return res.json({ report });
    } catch (error: any) {
      console.error('Gemini HSE audit error:', error);
      return res.status(500).json({ error: error.message || 'Error occurred during AI Audit execution.' });
    }
  });

  // Serve static client assets or pass to Vite in development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Personnel On Board System Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
